### ISSUE TITLE
Incompatible with expected Writer interface

### ISSUE THREAD

**Issue by stevenh** [orandin/slog-gorm#15]
The naming of the expected logger [interface for gorm](https://pkg.go.dev/gorm.io/gorm/logger#Interface) infers that the parameters are to be given to a `Print` like method however the [New method](https://pkg.go.dev/gorm.io/gorm/logger#New) which is the standard way to create a `Logger` takes a [Writer ](https://pkg.go.dev/gorm.io/gorm/logger#Writer) which defines `Printf` not `Print` so the expectation is `Printf(format string), a ...any)` not `Print(a ...any)`

The impact of that is errors thrown from gorm cause corrupt output:
```
msg="failed to initialize database, got error %v" !BADKEY="failed to connect to `host=localhost user=test_user database=test_database`: failed SASL auth (FATAL: password authentication failed for user \"test_user\" (SQLSTATE 28P01))"`
```

**Comment by injeniero** [comment]
I also found the same issue, @orandin please let me know if you would like me to create a PR to fix this soon. Thanks!

**Comment by orandin** [comment]
If you can create a PR to fix it before me, don't hesitate ! 😉

**Comment by injeniero** [comment]
@orandin #17
