### ISSUE TITLE
Allow setting slog attribute via Context function

### ISSUE THREAD

**Issue by teleivo** [orandin/slog-gorm#24]
Thanks a lot for your library @orandin 😄 

I have a suggestion about

```go
slogGorm.WithContextValue("slogAttrName", "ctxKey"), // adds an slog.Attr if a value if found for this key in the Gorm's query context
```

AFAIK its best practice not to expose the keys to ones context

https://medium.com/@matryer/context-keys-in-go-5312346a868d

With that in mind I think something like

```go
slogGorm.WithContextFunc("slogAttrName", func(ctx context.Context) (slog.Value, bool) {
})
```

might be useful. I for example work on a Gin app that uses an slog middleware generating a request ID. This middleware manages the ID and does not expose its key. It does provide a [function to get the ID](https://github.com/samber/slog-gin/blob/03c1ea443395806f966e0f4bce6c0110fc69d502/middleware.go#L261) though. With something like `WithContextFunc` I could thread the request ID into slow query logs 😄

I could implement it if you think this makes sense.

**Comment by teleivo** [comment]
I think I'll implement what I need outside of slog-gorm using a custom `slog.Handler` 👌🏻

**Comment by orandin** [comment]
This could be interesting to avoid writing a custom `slog.Handler` and especially when you can't write it. For me, this make sense, don't hesitate to implement and create a pull request, @teleivo

**Comment by teleivo** [comment]
Thanks @orandin 😄 just wanted to say that I will open a PR soon.
